import Layout from "@/components/layout/Layout";
import { headerLinks } from "@/constants/headerLinks";
import { useCurrentUserRole } from "@/hooks/currentUser";
import { Button, Select, Text } from "@mantine/core";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>dsgdhfjgj</h1>
    </>
  );
}
